# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DaengnyangDiary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DaengnyangDiary
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'RxDataSources', '~> 4.0'
  pod 'Moya', '~> 14.0'
  pod 'Moya/RxSwift', '~> 14.0'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'SwiftGen'

end
